### PR TITLE
Bug fix: device problem in Jacobian functions when working with GPU

### PR DESCRIPTION
**Pull request by GabrielMissael**
## Bug 🐛 
I was getting this error while trying to get the Jacobian to plot the critical line:

```
   1036         # Build Jacobian
   1037         J = self._jacobian_deflection_angle_autograd(x, y, z_s, params, **kwargs)
-> 1038         return torch.eye(2) - J.detach()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

To reproduce the error, assuming your DEVICE is CUDA:

```python
import caustics
import torch
import numpy as np
import matplotlib.pyplot as plt

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

n_pix = 32
res = 0.05
upsample_factor = 2
fov = res * n_pix
thx, thy = caustics.utils.get_meshgrid(
    res / upsample_factor,
    upsample_factor * n_pix,
    upsample_factor * n_pix,
    dtype=torch.float32,
    device = DEVICE
)
z_l = torch.tensor(0.5, dtype=torch.float32, device=DEVICE)
z_s = torch.tensor(1.5, dtype=torch.float32, device=DEVICE)
cosmology = caustics.cosmology.FlatLambdaCDM(name="cosmo")
cosmology.to(dtype=torch.float32)

sie = caustics.lenses.SIE(cosmology, name="sie")

x_sie = torch.tensor(
    [
        z_l.item(),  # sie z_l
        0.2,  # sie x0
        0.2,  # sie y0
        0.4,  # sie q
        np.pi / 5,  # sie phi
        0.5,  # sie b
    ]
).to(DEVICE)

# Pack parameters of system
packparams = sie.pack(x_sie)

# Jacobian of the lens equation
A = sie.jacobian_lens_equation(thx, thy, z_s, packparams)

# Determinant of the Jacobian
detA = torch.linalg.det(A).cpu().numpy()

# Plot the critical line
im = plt.imshow(
    detA, extent=(thx.cpu()[0][0], thx.cpu()[0][-1], thy.cpu()[0][0], thy.cpu()[-1][0]), origin="lower"
)
plt.colorbar(im)
CS = plt.contour(thx.cpu(), thy.cpu(), detA, levels=[0.0], colors="b")

plt.show()
```

## Solution 👁️ 

The code breaks because the tensor `J` (and all others) are in CUDA, but the new tensor created with `torch.eye(2)` is in CPU by default. So, the fix is to do `torch.eye(2).to(J.device)`  in the 4 lines that have this! 😄. When changing this, and re-running the script above, it works.

## NOTE!!! 🛑 

I did not run the unit tests... 😵. Also, the script above only "tests" the fix in line 1038, but not the other 3 changes... I just assumed that it's the same for the other functions. Feel free to close this PR

### CODE REVIEW

**Comment by AlexandreAdam** [comment]
That's a good catch. I thought we already fixed that bug a while back actually, since I ran into the same issue. Anyways, we need to merge this asap.

**Review by AlexandreAdam — APPROVED** [review]
This needs to be merged asap into main as an urgent bug fix.

**Review by ConnorStoneAstro — APPROVED** [review]

**Comment by ConnorStoneAstro** [comment]
@GabrielMissael merge the current dev branch into your branch. Then the checks will run

**Comment by GabrielMissael** [comment]
Hey @ConnorStoneAstro! Sorry, I just saw this!!

Thanks for merging the current dev branch! Could I help with anything else? 😄

**Comment by ConnorStoneAstro** [comment]
This looks good, I'm not sure what the issue is with the docs, but once we figure it out we will merge everything in

**Pull request merged**
