### PR TITLE
Turned pydantic into a weak dependancy

### PR DESCRIPTION
**Pull request by AlexandreAdam**
# Hot Fix

Turning `pydantic` into a weak dependency.

### CODE REVIEW

**Comment by ConnorStoneAstro** [comment]
Since pydantic isnt a req anymore, you'll need to modify the github action scripts to manually install pydantic so that the tests run

**Comment by AlexandreAdam** [comment]
I've added pydantic to the CI workflow, I'll need to iterate with the automatic testing because I'm not sure if it's enough

**Comment by AlexandreAdam** [comment]
Good catch, although to address this I need to change a few more things. I need to make sure the file with pydantic import is not part of the Caustics root import, and is only imported in the function that requires it, which is in the simulator I believe

**Comment by AlexandreAdam** [comment]
Correct me if I am wrong, but I think the approach I took solve the problem. The only thing exposed to the root level imports is build_simulator, so I made sure all the import statements related to Pydantic were used only inside the function definition. As such, Pydantic is now made a weak dependency. Caustics should attempt to import it only if build_simulator is called

**Review by ConnorStoneAstro — APPROVED** [review]
Looks good to me! the imports should only happen when calling build simulator

**Pull request merged**
