### PR TITLE
docs: extend timeout to allow matplotlib to build font library

### PR DESCRIPTION
**Pull request by ConnorStoneAstro**
Matplotlib is timing out our automated jupyter-notebook builds while trying to make a font library. The new timeout limit is set to 2 minutes to give it a chance to build

### CODE REVIEW

**Comment by ConnorStoneAstro** [comment]
Should we push this directly to main? since it is crashing there too

**Comment by lsetiawan** [comment]
> Should we push this directly to main? since it is crashing there too

Let's do that, this is a great patch.

**Review by lsetiawan — APPROVED** [review]

**Review by lsetiawan — CHANGES_REQUESTED** [review]
Welp, since this is branched of dev looks like you'll have to create a new PR since this has logs from current `dev` rather than from `main`.

**Comment by lsetiawan** [comment]
I think this other PR will fix the issue at hand: https://github.com/Ciela-Institute/caustics/pull/128

**Pull request closed without merging**
