### PR TITLE
docs: Attempt to add light/dark logo for website

### PR DESCRIPTION
**Pull request by ConnorStoneAstro**

### CODE REVIEW

**Comment by ConnorStoneAstro** [comment]
So I found an option to specify a light/dark logo for the website. I couldn't figure out how to change other images though so I just removed the big logo we keep in the homepage. I think this looks pretty slick :)

**Comment by lsetiawan** [comment]
> So I found an option to specify a light/dark logo for the website

Nicely Done! 🎉  Yea this looks great! Thanks for the detective work to finding this configuration 😄

**Review by lsetiawan — APPROVED** [review]

**Comment by ConnorStoneAstro** [comment]
@lsetiawan it looks like the CD check isn't running, do you have any idea why?

**Comment by lsetiawan** [comment]
> @lsetiawan it looks like the CD check isn't running, do you have any idea why?

The CD will only run on `dev` or `main` branch, not on PRs since this is actually building and pushing package to test PyPI.

**Pull request merged**
